FROM node:14-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL
RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]  # Corrected: added commas between the arguments
