FROM golang:1.19-alpine
WORKDIR /app
COPY go.sum ./
RUN go mod init backend \
    && go get gorm.io/gorm \
    && go get gorm.io/driver/postgres \
    && go get github.com/gorilla/mux \
    && go get github.com/lib/pq \
    && go get ./...
COPY . .
RUN go build -o backend .
EXPOSE 8080
CMD [ "go", "run", "main.go" ]
